name: Deploy Static Site with Firebase Config

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Replace environment variable placeholders in script.js with actual values
      - name: Replace Firebase Environment Variables
        run: |
          sed -i 's/process.env.FIREBASE_API_KEY/${{ secrets.FIREBASE_API_KEY }}/g' ./assets/script.js
          sed -i 's/process.env.FIREBASE_AUTH_DOMAIN/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g' ./assets/script.js
          sed -i 's/process.env.FIREBASE_PROJECT_ID/${{ secrets.FIREBASE_PROJECT_ID }}/g' ./assets/script.js
          sed -i 's/process.env.FIREBASE_DATABASE_URL/${{ secrets.FIREBASE_DATABASE_URL }}/g' ./assets/script.js
          sed -i 's/process.env.FIREBASE_STORAGE_BUCKET/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g' ./assets/script.js
          sed -i 's/process.env.FIREBASE_MESSAGING_SENDER_ID/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g' ./assets/script.js
          sed -i 's/process.env.FIREBASE_APP_ID/${{ secrets.FIREBASE_APP_ID }}/g' ./assets/script.js

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
